In [1]:
import numpy as np

In [3]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
X

array([[ -4.99897431,  12.59314191,  -3.74159616, ...,  -2.3149991 ,
         -7.99430512,   4.04135971],
       [ -4.29149572,   5.35420027, -16.40693439, ...,   8.18336878,
         -3.19883766,   4.25225525],
       [  5.18565983,  15.93951497,  -3.43167202, ...,  -4.62714133,
         -8.68680129,  -6.56503003],
       ...,
       [  8.80208782,  14.82932639,   2.68396309, ...,   0.7907207 ,
          7.27036894,   0.53847708],
       [  7.4065838 , -10.33389546,   3.00600785, ...,   6.89066597,
         -5.25816626,  12.52698662],
       [ -4.07879166, -15.35260219, -15.00748587, ...,  -0.78793628,
          6.38196376,  -7.56641991]])

In [6]:
X_m = np.mean(X, axis=0)
X_std = np.std(X, axis=0)
X_norm = (X - X_m) / X_std
X_norm

array([[-0.635873  ,  1.20385181, -0.49864236, ..., -0.31578534,
        -0.96175898,  0.30242514],
       [-0.5632594 ,  0.45841573, -1.75769609, ...,  0.7206435 ,
        -0.48300449,  0.32313491],
       [ 0.40944898,  1.54844738, -0.46783299, ..., -0.54404662,
        -1.03089419, -0.73911366],
       ...,
       [ 0.7806289 ,  1.43412478,  0.14011866, ..., -0.00917981,
         0.56218655, -0.04155507],
       [ 0.63739832, -1.15707908,  0.17213294, ...,  0.59302419,
        -0.68859713,  1.13570676],
       [-0.54142806, -1.67388461, -1.61857775, ..., -0.16502934,
         0.47349281, -0.83744933]])

In [7]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [10]:
np.nonzero(np.sum(Z, axis=1) > 10)

(array([1, 4, 5]),)

In [15]:
A = np.eye(3)
B = np.eye(3)
np.vstack((A, B))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Теперь непосредственно задание:
    1. Какое количество мужчин и женщин ехало на корабле? В качестве ответа приведите два числа через пробел.
    2. Какой части пассажиров удалось выжить? Посчитайте долю выживших пассажиров. Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.
    3. Какую долю пассажиры первого класса составляли среди всех пассажиров? Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.
    4. Какого возраста были пассажиры? Посчитайте среднее и медиану возраста пассажиров. В качестве ответа приведите два числа через пробел.
    5. Коррелируют ли число братьев/сестер/супругов с числом родителей/детей? Посчитайте корреляцию Пирсона между признаками SibSp и Parch.
    6. Какое самое популярное женское имя на корабле? Извлеките из полного имени пассажира (колонка Name) его личное имя (First Name). Это задание — типичный пример того, с чем сталкивается специалист по анализу данных. Данные очень разнородные и шумные, но из них требуется извлечь необходимую информацию. Попробуйте вручную разобрать несколько значений столбца Name и выработать правило для извлечения имен, а также разделения их на женские и мужские.

Если ответом является нецелое число, то целую и дробную часть необходимо разграничивать точкой, например, 0.42. При необходимости округляйте дробную часть до двух знаков.

Ответ на каждое задание — текстовый файл, содержащий ответ в первой строчке. Обратите внимание, что отправляемые файлы не должны содержать перевод строки в конце. Данный нюанс является ограничением платформы Coursera. Мы работаем над тем, чтобы убрать это ограничение.

In [92]:
import pandas as pd
from pathlib import Path
path = Path.cwd()
path = path.joinpath('../data/raw/HSE_ML_week1')

data = pd.read_csv(path.joinpath('titanic.csv'), index_col='PassengerId')
data.head(20)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   
11                  1       3   
12                  1       1   
13                  0       3   
14                  0       3   
15                  0       3   
16                  1       2   
17                  0       3   
18                  1       2   
19                  0       3   
20                  1       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
11                             Sandstrom, Miss. Marguerite Rut  female   4.0   
12                                    Bonnell, Miss. Elizabeth  female  58.0   
13                              Saundercock, Mr. William Henry    male  20.0   
14                                 Andersson, Mr. Anders Johan    male  39.0   
15                        Vestrom, Miss. Hulda Amanda Adolfina  female  14.0   
16                            Hewlett, Mrs. (Mary D Kingcome)   female  55.0   
17                                        Rice, Master. Eugene    male   2.0   
18                                Williams, Mr. Charles Eugene    male   NaN   
19           Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0   
20                                     Masselmani, Mrs. Fatima  female   NaN   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
6                0      0            330877   8.4583   NaN        Q  
7                0      0             17463  51.8625   E46        S  
8                3      1            349909  21.0750   NaN        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C  
11               1      1           PP 9549  16.7000    G6        S  
12               0      0            113783  26.5500  C103        S  
13               0      0         A/5. 2151   8.0500   NaN        S  
14               1      5            347082  31.2750   NaN        S  
15               0      0            350406   7.8542   NaN        S  
16               0      0            248706  16.0000   NaN        S  
17               4      1            382652  29.1250   NaN        Q  
18               0      0            244373  13.0000   NaN        S  
19               1      0            345763  18.0000   NaN        S  
20               0      0              2649   7.2250   

In [31]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [51]:
np.round(data['Survived'].sum() / data.Survived.count(), decimals=4) * 100

38.379999999999995

In [50]:
data['Pclass'].value_counts()[1] / data['Pclass'].value_counts().sum() * 100

24.242424242424242

In [54]:
print(data['Age'].mean(), data['Age'].median())

29.69911764705882 28.0


In [98]:
np.corrcoef(data['SibSp'], data['Parch'])

array([[1.       , 0.4148377],
       [0.4148377, 1.       ]])

In [93]:
data[data['Sex'] == 'female']['Name'].apply(lambda x: x.partition("Miss. ")[2].partition(' ')[0]).value_counts().head(10)

             132
Anna           9
Mary           9
Margaret       6
Elizabeth      5
Bertha         4
Helen          4
Ellen          4
Alice          4
Katherine      3
Name: Name, dtype: int64

In [94]:
data[data['Sex'] == 'female']['Name'].apply(lambda x: x.partition('(')[2].partition(' ')[0]).value_counts().head(10)

             185
Elizabeth      6
Anna           5
Maria          4
Ada            4
Margaret       4
Mary           4
"Mrs           3
Florence       3
Jane           3
Name: Name, dtype: int64

In [99]:
path

PosixPath('/home/topcoder2k/ds-intro/notebooks/../data/raw/HSE_ML_week1')

In [103]:
file = open('/home/topcoder2k/HSE_ML_week1_answers/popular_name.txt', 'w')
file.write('Anna')
file.close()